/*
 * This source file was generated by the Gradle 'init' task
 */
package com.sdp.sudoku;

import org.testng.annotations.*;

public class LoaderTest {
    @Test public void appHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
