/*
 * This source file was generated by the Gradle 'init' task
 */
package com.sdp.sudoku;

import com.sdp.sudoku.config.CDG;
import com.sdp.sudoku.io.*;
import com.sdp.sudoku.tablero.*;

public class Main {
    Output out = Output.getInstance();

    public static void main(String[] args) {
        Main app = new Main();
        int rc = app.playGame(args);
        if (rc == CDG.DONE) System.out.println("Hecho!");
        System.exit(rc);
    }
    private int playGame(String[] args) {
        Input input = new Input();
        Integer[] data = input.load(args);
        Board board = prepareBoard(data);
        return play(board);
    }

    private int play (Board board) {
        Board pBoard;

        while (true) {
            Square option = board.getCandidate();
            int card = option.cardinality();
            switch (card) {
                case 0: return CDG.DONE;
                case 1:
                    out.setMessage("Obtenida opcion de cardinalidad 1");
                    out.setMessage("Casilla: " + option.getPos());
                    roundSimple(board, option); break;
                default:
                    out.setMessage("Obtenida opcion de cardinalidad: " +  card);
                    out.setMessage("Casilla: " + option.getPos());

                    for (int i = 0; i < option.cardinality(); i++) {
                        pBoard = board.copy();
                        board.bet(i);
                        // Ponemos el valor como unica opcion
                        play(pBoard);
                    }
            }
        }
        return CDG.DONE;
    }
    private Board prepareBoard(Integer[] data) {
        BoardFactory factory = new BoardFactory();

        Board board = factory.getBoard(data);
        board.init();
        out.setMessage("Situacion inicial");
        out.print(board.getCurrentBoard());
        return board;
    }
    private Board roundSimple(Board board, Square option) {
        option.setValue(0);
        board.round(option);
        out.setMessage("Jugando casilla " + option.getPos());
        out.setMessage("Jugando valor " + option.getValue());
        out.print(board.getCurrentBoard());
        return board;
    }
}
