/*
 * This source file was generated by the Gradle 'init' task
 */
package com.sdp.sudoku;

import com.sdp.sudoku.ctes.ANSI;
import com.sdp.sudoku.ctes.CDG;
import com.sdp.sudoku.io.*;
import com.sdp.sudoku.boards.*;

import java.util.ArrayList;
import java.util.List;
import java.io.PrintWriter;

public class Main {
    Output out = Output.getInstance();
    long start = 0;

    StringBuilder stree = new StringBuilder("1 ");

    public static void main(String[] args) {
        Sudoku sudoku = new Sudoku();

        Integer[] data = processCommandLine(args);

        long start = System.currentTimeMillis();
        int rc = sudoku.playGame(data);

        printResult(sudoku.getBoard());
        printSummary(rc, start);

        System.exit(rc);
    }
    private static Integer[]  processCommandLine(String[] args) {
        Input input = new Input();
        return input.load(args);
    }
    private static void printResult(Board board) {
    }

    private static void printSummary(int rc, long start) {
        PrintWriter printer = new PrintWriter(System.out);
        printer.print("Resultado: ");
        printer.println((rc == CDG.DONE) ? ANSI.use(ANSI.BOLD,"Resuelto")
                                         : ANSI.use(ANSI.RED, "Erroneo"));
        printer.print("Tiempo:    ");
        printer.println(ANSI.use(ANSI.BOLD, Long.toString(System.currentTimeMillis() - start) + " ms"));
    }

}
