/*
 * This source file was generated by the Gradle 'init' task
 */
package com.sdp.sudoku;

public class Sudoku {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Sudoku app = new Sudoku();
        app.load(args);
        int rc = app.play();
    }
    private void load(String[] args) {

    }
    private int play() {
        return 0;
    }
}
